package common

const (
	PIECE_TYPE_PAWN   = 1
	PIECE_TYPE_KNIGHT = 2
	PIECE_TYPE_ROOK   = 3
	PIECE_TYPE_BISHOP = 4
	PIECE_TYPE_KING   = 5
	PIECE_TYPE_QUEEN  = 6
)

const (
	MOVEMENT_TYPE_PAWN   = 1
	MOVEMENT_TYPE_KNIGHT = 2
	MOVEMENT_TYPE_ROOK   = 3
	MOVEMENT_TYPE_BISHOP = 4
	MOVEMENT_TYPE_KING   = 5
	MOVEMENT_TYPE_QUEEN  = 6
)
